window.browser = {};

window.browser.i18n = {};
window.browser.i18n.getUILanguage = () => navigator.language;
window.browser.i18n.getMessage = (assOriginal, url) => assOriginal === 'assOriginal' ? `Generated by ASS Danmaku Convert Online based on ${url}` : null;

window.browser.storage = {};
window.browser.storage.sync = {};
window.browser.storage.sync.get = async (obj) => (
  Object.assign({}, ...Object.keys(obj).map(key => ({ [key]: localStorage.getItem(key) || obj[key] })))
);
window.browser.storage.sync.set = async (obj) => (
  Object.keys(obj).forEach(key => localStorage.setItem(key, obj[key]))
);
